name       : perl-json-xs
version    : '4.03'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/JSON-XS-4.03.tar.gz : 515536f45f2fa1a7e88c8824533758d0121d267ab9cb453a1b5887c8a56b9068
homepage   : https://metacpan.org/pod/JSON::XS
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : json_xs - JSON::XS commandline utility
description: |
    json_xs converts between some input and output formats (one of them is JSON). The default input format is json and the default output format is json-pretty.
builddeps  :
    - perl-canary-stability
    - perl-common-sense
    - perl-types-serialiser
rundeps    :
    - perl-types-serialiser
setup      : |
    export PERL_CANARY_STABILITY_NOPROMPT=1
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
