name       : perl-json-xs
version    : '3.04'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/JSON-XS-3.04.tar.gz : 65d8836bd8ea6f0b7bffc70b2212156adc3e2ffa587e27e548d576893f097c2c
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : json_xs - JSON::XS commandline utility
description: |
    json_xs converts between some input and output formats (one of them is JSON). The default input format is json and the default output format is json-pretty.
builddeps  :
    - perl-canary-stability
    - perl-common-sense
    - perl-types-serialiser
rundeps    :
    - perl-types-serialiser
setup      : |
    export PERL_CANARY_STABILITY_NOPROMPT=1
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
